# Generated by Django 3.1.2 on 2021-05-24 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventGateway', '0002_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRegisteration',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField()),
                ('open', models.BooleanField(default=True)),
                ('participants', models.AutoField(primary_key=True, serialize=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='eventGateway.events')),
            ],
        ),
    ]
