# Generated by Django 3.1.2 on 2021-05-24 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventGateway', '0003_eventregisteration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregisteration',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventGateway.events'),
        ),
    ]
