# Generated by Django 3.1.2 on 2021-05-24 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventGateway', '0004_auto_20210524_2136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventregisteration',
            name='event',
        ),
    ]
