# Generated by Django 3.1.2 on 2021-05-24 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventGateway', '0005_remove_eventregisteration_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventRegisteration',
        ),
    ]
